### ISSUE TITLE
bwrap: Can't make symlink at /var/run: File exists

### ISSUE THREAD

**Issue by schildbach** [flathub/org.bitcoincore.bitcoin-qt#17]
On Ubuntu 20.04.4 LTS with the Flatpak 1.6.5 that comes with it:

```
$ flatpak install flathub org.bitcoincore.bitcoin-qt
[...]
Installation complete.

$ flatpak info org.bitcoincore.bitcoin-qt

Bitcoin Core - Connect to the Bitcoin P2P network

          ID: org.bitcoincore.bitcoin-qt
         Ref: app/org.bitcoincore.bitcoin-qt/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 22.0
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 71.2 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 9f4757a714942e5c9214e29648dc817ba60eafcbd46821541dccfb7951f1b4cd
      Parent: f52c20ece3b6a096cb1c40a0af5d68ef50b782f9cf8e0cc26298c7d6f66fdad9
     Subject: Add x-data-checker (2d5b49c3)
        Date: 2022-02-09 07:35:20 +0000

$ flatpak run org.bitcoincore.bitcoin-qt
bwrap: Can't make symlink at /var/run: File exists
```

**Comment by MarcoFalke** [comment]
Looks like a bug in flatpak that was incorrectly closed: https://github.com/flatpak/flatpak/issues/2200

**Comment by schildbach** [comment]
I'll try again on Jammy (Flatpak 1.12.7) once I've updated.

**Comment by harrymmmm** [comment]
same issue with org.bitcoincore.bitcoin-qt on jammy and flatpak 1.12.7.

**Comment by un-def** [comment]
I managed to reproduce the bug. It has nothing to do with the Flatpak version, the bug is in the manifest itself. Actually, it was introduced as a “feature” [here](https://github.com/flathub/org.bitcoincore.bitcoin-qt/pull/9), but I wonder if it has ever worked correctly. At least I was not able to trace the change that potentially could break what (presumably) worked fine, and I've dived back to 1.3-ish Flatpak versions.

The thing is [right here](https://github.com/flathub/org.bitcoincore.bitcoin-qt/commit/e6d2ce153ad1a396ccbbd25ddc88334f90fa50d6#diff-c79a92c31882bc3a4467f0b2f5faa2d2faafb57da723e484481da18f65e56fefR20-R21). You see, we have here not just one, but two filesystem permissions pointing to basically the same file. On virtually any modern Linux system (FHS 3.0 was released on 2015-05-18)  `/var/run` is a symlink to `/run`, and this seemingly subtle quirk has [unforeseen consequences](https://github.com/flatpak/flatpak/commit/28e96288c487faa23845aa19c0b34dfce45dd6a7):

> if [...] it contains /var/run -> ../run, then flatpak thinks we need to add the /var/run symlink in the runtime even though we already exposed that.

The aforementioned commit is not about this exact bug, but, if I understand correctly, the underlying processes are the same:

1. Flatpak sees `/run/whatever`, create a symlink inside the sandbox.
1. Flatpak sees `/var/run/whatever`, tries to create a symlink inside the sandbox and fails because `/var/run/whatever` _is_ `/run/whatever`, and the corresponding symlink has already been created (hence `Can't make symlink at /var/run: File exists`; it indeed exists, we just created it).

At least with my miserable debugging skills I managed to trace the following:

```shell
$ strace -f -e trace=symlink,readlinkat flatpak --system run org.bitcoincore.bitcoin-qt/x86_64/stable 2>&1 | grep -E '".*/run"|".*/var/run"'
[pid 187575] readlinkat(AT_FDCWD, "/var/run", "/run", 99) = 4
[pid 187575] readlinkat(AT_FDCWD, "/var/run", "/run", 99) = 4
[pid 187584] symlink("../run", "/newroot/var/run") = 0
[pid 187584] symlink("../run", "/newroot/var/run") = -1 EEXIST (File exists)
```

Two `symlink` syscalls, the first is successull, the second returns `EEXIST` (as expected).


# How to reproduce the bug

## Prerequisite

Use a distro where the Tor `CookieAuthFile` option is set to `/run/tor/control.authcookie` (Debian, Ubuntu, Fedora, you name it). This is **NOT** the default value, see `man 5 torrc`:

```
DataDirectory DIR
   Store working data in DIR. Can not be changed while tor is running. (Default: ~/.tor if your home directory is not /; otherwise, /var/lib/tor. On Windows, the default is your ApplicationData folder.)
```

```
DataDirectory/control_auth_cookie
    This file can be used only when cookie authentication is enabled. Used for cookie authentication with the controller. Location can be overridden by the CookieAuthFile configuration option. Regenerated on startup. See control-spec.txt in torspec for details.
```

That is, the default value (if `CookieAuthFile` is not set) is `/var/lib/tor/control_auth_cookie` / `~/.tor/control_auth_cookie`, not `/run/tor/control.authcookie`. But (some) distro maintainers decided that the default is not good enough. Why? Because *they* know better, silly you! Okay-okay, presumably `/run/` fits better to the FHS, and it is the Tor developers who are wrong.

## Steps to reproduce

1. Install and start Tor service (`systemctl start tor`)
2.  ```shell
    $ ls /run/tor
    control  control.authcookie  socks  tor.pid

    $ ls /var/run/tor
    control  control.authcookie  socks  tor.pid

    $ file /var/run
    /var/run: symbolic link to /run
    ```
3.  ```shell
    $ flatpak run org.bitcoincore.bitcoin-qt
    bwrap: Can't make symlink at /var/run: File exists
    ```
4. Stop Tor service (`systemctl stop tor`)
5.  ```shell
    $ ls /run/tor -l
    total 0
6.  ```shell
    $ flatpak run org.bitcoincore.bitcoin-qt
    ```
    Bitcoin Core starts without problems.
